name: Publish Docker Image

on:
  push:
    tags:
      - "v*"  # Запускать при создании тега (например, v1.0.0)

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/docker_package_test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Разрешение на запись в GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Автоматический токен

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Путь к каталогу с Dockerfile
          file: ./Dockerfile  # Путь к Dockerfile (если не в корне)
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          push: true  # Автоматически пушить образ
